spring:
  profiles:
    active: dev, basic, cache
server:
  port: 8181
logging:
  level:
    root: info
    org.hibernate: off
    org.springframework.web: off
    ru.clevertec.nms.aop.logging.ControllerLayerLogAspect: debug
    ru.clevertec.nms.controller: debug

---

spring:
  config:
    activate:
      on-profile: basic
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        search:
          backend:
            analysis:
              configurer: ru.clevertec.nms.configuration.search.CustomLuceneAnalysisConfigurer
            directory:
              root: /data/index/default
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 20

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db:5432/newsdbp
    username: newsdbp
    password: compose-postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/db.changelog-master.yaml
    enabled: true
application:
  need-reindex: true

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/newsdb
    username: postgres
    password: SUP3RpostU$3R
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
application:
  need-reindex: false

---

spring:
  config:
    activate:
      on-profile: redis
  data:
    redis:
      host: localhost
      port: 6379

---

spring:
  config:
    activate:
      on-profile: cache
application:
  cache:
    algorithm: LRU
    capacity: 2
